name: igindo_home
description: Igindo website
version: 0.1.0
environment:
  sdk: '>=2.0.0-dev.62.0 <3.0.0'

dependencies:
  angular: ^5.0.0
  angular_router: ^2.0.0-alpha+17
  angular_forms: ^2.0.0
  rxdart: ^0.19.0
  stagexl: ^1.4.0
  corona_core:
    git: git@github.com:frankpepermans/corona_core.git

dev_dependencies:
  sass: ^1.3.2
  test: ^1.3.0
  build: ^0.12.7
  source_gen: ^0.8.3
  angular_test: ^2.0.0
  build_runner: ^0.9.2
  build_test: ^0.10.3
  build_web_compilers: ^0.4.1
  corona:
    git: git@github.com:frankpepermans/corona.git

dependency_overrides:
  corona:
    path: ../corona
  corona_core:
    path: ../corona_core

web:
  compiler:
    debug: dartdevc
